apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "vaktmester"
  namespace: "aap"
  labels:
    "team": "aap"
    "sub": "vedtak"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{this.name }}
       value: {{this.value}}
  {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: devtools
